ALTER TABLE tutors ADD COLUMN grades_json TEXT;
ALTER TABLE tutors ADD COLUMN bank_name TEXT;
ALTER TABLE tutors ADD COLUMN bank_account_name TEXT;
ALTER TABLE tutors ADD COLUMN bank_account_number TEXT;
ALTER TABLE tutors ADD COLUMN bank_branch TEXT;
ALTER TABLE classes ADD COLUMN class_date TEXT;
ALTER TABLE classes ADD COLUMN status TEXT;
ALTER TABLE classes ADD COLUMN tutor_name TEXT;
ALTER TABLE classes ADD COLUMN subject_name TEXT;
